version: "3"
services:
  user-service:
    build:
      context: ../user_service
    ports:
      - "${GRPC_PORT}:${GRPC_PORT}"
    environment:
      GRPC_PORT: ${GRPC_PORT}
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@users-db:${POSTGRES_PORT}/${POSTGRES_DB}
    depends_on:
      - users-db
    networks:
      - chat-network
  users-db:
    image: "postgres"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    networks:
      - chat-network

networks:
  chat-network:
    name: chat-network
